# Generated by Django 5.2 on 2025-05-06 11:26

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Car',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('country', models.CharField(max_length=30)),
                ('score', models.PositiveSmallIntegerField(max_length=10, validators=[django.core.validators.MaxValueValidator(10)])),
            ],
        ),
    ]
